### ISSUE TITLE
http://docs.javaslang.io/ seems to have a redirect loop

### ISSUE THREAD

**Issue by HaraldKi** [vavr-io/vavr-docs#24]
When trying to navigate to the documentation Firefox and Chromium both complain about wrong redirects. Firefox specifically talks about a redirect loop.

**Comment by danieldietrich** [comment]
Wow - that is interesting! Thank you for the hint. Will investigate it ASAP!

**Comment by danieldietrich** [comment]
I created a temporary fix by removing the CNAME file. The URL changes now when loading http://docs.javaslang.io but it works.

I think it is a Github error. Nothing else changed. I will check that.

**Comment by danieldietrich** [comment]
I re-installed the CNAME file. The bug passed away. Nothing changed - the reason is still unclear.

**Comment by ruslansennov** [comment]
I confirm, it doesn't work now.
http://docs.javaslang.io redirects to http://javaslang.github.io/javaslang-docs and then 
```
The javaslang.github.io page isn’t working

javaslang.github.io redirected you too many times.
```
Chrome Version 50.0.2661.102 (64-bit)

**Comment by danieldietrich** [comment]
I had the same problem earlier, now it does work for me. On my mobile phone using Safari, on my notebook using Safari 9.1.1, Chrome 50.0.2661.102 (64-bit) and 51.0.2704.63 (64-bit), Firefox 45.0.2 and Firefox 46.0.1.

Maybe it is a DNS problem on the network? Or the DNS information is cached somewhere?

**Comment by ruslansennov** [comment]
> Maybe it is a DNS problem on the network? Or the DNS information is cached somewhere?

I'll check it tomorrow

**Comment by danieldietrich** [comment]
Me too

**Comment by danieldietrich** [comment]
Got the error again and temporarily fixed it by removing CNAME file.

**Comment by danieldietrich** [comment]
javaslang is now vavr.

https://docs.vavr.io
