### ISSUE TITLE
update of the match instanceOf

### ISSUE THREAD

**Issue by kevlarC** [vavr-io/vavr-docs#31]
Tried to update this myself but I cant push so 
line 248 of usage_guide it should look something like 
```
import static io.vavr.API.$;
import static io.vavr.API.Case;
import static io.vavr.API.Match;
import static io.vavr.Predicates.instanceOf;

A result = Try.of(this::bunchOfWork)
    .recover(x -> Match(x).of(
        Case($(instanceOf(Exception_1.class)), t -> somethingWithException(t)),
        Case($(instanceOf(Exception_2.class)), t -> somethingWithException(t)),
        Case($(instanceOf(Exception_n.class)), t -> somethingWithException(t))
    ))
    .getOrElse(other);
```
I added the imports since there are quite a few libaries out there with a static method instanceOf and it took a while to find the right one.

**Comment by danieldietrich** [comment]
Thank you, I fixed it.

I also updated the whole documentation to Vavr-0.9.0 and removed the old name 'Javaslang'.

If you find further discrepancies don't hesitate to create an issue!
