### ISSUE TITLE
Best practice for generating html5 with asciidoctor

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr-docs#4]
See comments in pom

**Comment by danieldietrich** [comment]
See also this example: https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-html-example/pom.xml

**Comment by jasoet-gdp** [comment]
I think we will get "our" best practice after we encounter real work. After i read the comment, main focus is about location of resources such as `images`, `css` etc. Also we can create guidelines to write docs about how we store our images etc.

**Comment by danieldietrich** [comment]
:+1:

Some instructions can walk into a README.md of the project

**Comment by pivovarit** [comment]
outdated long-time ago, closing - we're not even on Maven anymore
